xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://192.168.247.70:8080/xxl-job-admin
    ### xxl-job executor address
    executor:
      appname: vova
      ip:
      port: 9999
      ### xxl-job log path
      logpath: /Users/wangyang/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1
    ### xxl-job, access token
    accessToken:
server:
  port: 9093